services:
  postgres:
    image: postgres:18-alpine
    container_name: digilab-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digilab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: digilab-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tamquan.edu.vn
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
